/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Control;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pajas
 */
public class Practicando extends javax.swing.JFrame {

    Connection con = Control.con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    DefaultListModel listEscuelaModel = new DefaultListModel();

    public Practicando() {
        initComponents();
        init();
        fillCombo();
    }

    public void init() {
        setTitle("Facultades y escuelas");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        try {
            st = con.createStatement();
        } catch (SQLException ex) {
            System.err.print(ex);
        }
    }

    public void fillCombo() {
        Control.fillCombo(comboFacultad, "select nombre from facultad");
        comboFacultad.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedFacultad = e.getItem().toString();
                    fillList(selectedFacultad);
                }
            }
        });
    }

    public void fillList(String selectedFacultad) {
        listEscuelaModel.removeAllElements();
        listEscuela.setModel(listEscuelaModel);
        try {
            String sql = "select nombre from escuela"
                    + " where facultad_id=(select id from facultad"
                    + " where nombre=\"" + selectedFacultad + "\")";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                listEscuelaModel.addElement(rs.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Practicando.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboFacultad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEscuela = new javax.swing.JList<>();
        btnEliminarFacultad = new javax.swing.JButton();
        btnCrearFacultad = new javax.swing.JButton();
        btnEliminarEscuela = new javax.swing.JButton();
        btnCrearEscuela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        comboFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFacultadActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listEscuela);

        btnEliminarFacultad.setText("Eliminar Facultad");
        btnEliminarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFacultadActionPerformed(evt);
            }
        });

        btnCrearFacultad.setText("Crear Facultad");
        btnCrearFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacultadActionPerformed(evt);
            }
        });

        btnEliminarEscuela.setText("Eliminar Escuela");
        btnEliminarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEscuelaActionPerformed(evt);
            }
        });

        btnCrearEscuela.setText("Crear Escuela");
        btnCrearEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEscuelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(comboFacultad, 0, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(btnCrearEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarFacultad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCrearFacultad)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarEscuela)
                        .addComponent(btnCrearEscuela))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFacultadActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            con.close();
        } catch (SQLException ex) {
            System.out.println("No se pudo cerrar la conexion");
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnEliminarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFacultadActionPerformed
        /*Almacenar que facultad está seleccionado y despues eliminar esa facultad con executeUpdate*/
        if (comboFacultad.getSelectedIndex() != -1) {
            String facultad = comboFacultad.getSelectedItem().toString();
            int select = JOptionPane.showConfirmDialog(null, "Seguro que quiere borrar la facultad " + facultad);
            if (select == 0) {
                try {
                    String sql = "delete from facultad where nombre='" + facultad + "'";
                    if (st.executeUpdate(sql) > 0) {
                        JOptionPane.showMessageDialog(null, "Eliminación exitosa");
                        comboFacultad.removeItem(facultad);
                    } else {
                        JOptionPane.showMessageDialog(null, "Elminación fallida");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "La facultad tiene escuelas");
                    System.err.print(ex);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarFacultadActionPerformed

    private void btnCrearFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacultadActionPerformed
        // TODO add your handling code here:
        /*Pedir un input al usuario con el nombre de la facultad, el cual no debe de ser vacio ni solo con espacios
        , después añadir la facultad y si ya existe avisale al usuario, de modo de que no exista
        se tiene que rellenar el combo de nuevo*/
        String nuevaFacultad = JOptionPane.showInputDialog("Ingrese el nombre de la nueva facultad");
        nuevaFacultad = nuevaFacultad.trim();
        if (!nuevaFacultad.equals("")) {
            try {
                String sql = "insert into facultad(nombre) value('" + nuevaFacultad + "')";
                if (st.executeUpdate(sql) != 0) {
                    JOptionPane.showMessageDialog(null, "Ingreso exitoso");
                    comboFacultad.addItem(nuevaFacultad);
                }
            } catch (SQLException ex) {
                System.err.println(ex);
                JOptionPane.showMessageDialog(null, "Esa facultad ya existe");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre válido");
        }
    }//GEN-LAST:event_btnCrearFacultadActionPerformed

    private void btnEliminarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEscuelaActionPerformed
        /*
        Comprobar si una escuela o más están seleccionadas
        Elimina escuela
         */
        if (!listEscuela.isSelectionEmpty() && JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar las escuela/s?") == 0) {
            List escuelas = listEscuela.getSelectedValuesList();
            for (Object escuela : escuelas) {
                try {
                    String sqlDelete = "delete from escuela where nombre = '" + escuela + "'";
                    st.executeUpdate(sqlDelete);
                    listEscuelaModel.removeElement(escuela);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Grave error");
                    System.err.println(ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar una escuela");
        }
    }//GEN-LAST:event_btnEliminarEscuelaActionPerformed

    private void btnCrearEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEscuelaActionPerformed
        /*Comprobar si una facultad está seleccionada, entonces pedir un input al usuario
        , comprobar si dicho input no es vacío ni solo con espacios.
        , guardar la escuela*/
        if (comboFacultad.getSelectedIndex() != -1) {
            String newEscuela = JOptionPane.showInputDialog("Ingrese el nombre de la escuela");
            newEscuela = newEscuela.trim();
            if (newEscuela.length() != 0) {
                try {
                    String sqlInsert = "insert into escuela(nombre,facultad_id) values(?,?)";
                    String nombreFacultad = comboFacultad.getSelectedItem().toString();
                    String sqlidFacultad = "select id from facultad where nombre='" + nombreFacultad + "'";
                    int id_facultad = Integer.parseInt(Control.returnData(sqlidFacultad));
                    ps = con.prepareStatement(sqlInsert);
                    ps.setString(1, newEscuela);
                    ps.setInt(2, id_facultad);
                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Ingreso Exitoso");
                        listEscuelaModel.addElement(newEscuela);
                    } else {
                        JOptionPane.showMessageDialog(null, "Ingreso fallido");
                    }
                } catch (SQLException ex) {
                    System.err.println(ex);
                    JOptionPane.showMessageDialog(null, "Esa escuela ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un nombre valido");
            }
        }
    }//GEN-LAST:event_btnCrearEscuelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practicando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practicando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practicando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practicando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practicando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearEscuela;
    private javax.swing.JButton btnCrearFacultad;
    private javax.swing.JButton btnEliminarEscuela;
    private javax.swing.JButton btnEliminarFacultad;
    private javax.swing.JComboBox<String> comboFacultad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listEscuela;
    // End of variables declaration//GEN-END:variables
}
