/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Control;
import clases.Validar;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.util.Objects;

/**
 *
 * @author Pajas
 */
@SuppressWarnings({"RedundantSuppression", "FieldCanBeLocal"})
public class Escuela extends javax.swing.JFrame {

    /**
     * Creates new form Facultad
     */
    DefaultTableModel md;

    public Escuela() {
        initComponents();
        init();
        addTable();
        addComboFacultad();
    }

    public void init() {
        setLocationRelativeTo(null);
        setTitle("Datos de la escuela");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        Validar.textField(txBuscar);
        Validar.textField(txEscuela);
        txBuscar.setEnabled(false);
    }

    public void addTable() {
        md = new DefaultTableModel();
        md.setColumnIdentifiers(new String[]{"Escuelas"});
        tbEscuelas.setModel(md);
    }

    public void addComboFacultad() {
        String sqlCombo = "select nombre from facultad";
        Control.fillCombo(comboFacultad, sqlCombo);
        comboFacultad.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                String selectedFacultad = e.getItem().toString();
                String sqlTable = String.format("select e.nombre from escuela e inner join facultad f on"
                        + " f.id=e.facultad_id where f.nombre = '%s'", selectedFacultad);
                System.out.println(sqlTable);
                Control.fillTable(md, sqlTable, 1);
                txBuscar.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txEscuela = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboFacultad = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEscuelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos de la escuela:");

        jLabel2.setText("Escuela:");

        txEscuela.addActionListener(this::txEscuelaActionPerformed);

        jLabel3.setText("Facultad:");

        comboFacultad.addActionListener(this::comboFacultadActionPerformed);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnEditar.setText("Editar");

        btnCancelar.setText("Cancelar");

        btnEliminar.setText("Eliminar");

        btnSalir.setText("Salir");

        jLabel4.setText("Buscar:");

        txBuscar.addActionListener(this::txBuscarActionPerformed);
        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBuscarKeyTyped(evt);
            }
        });

        tbEscuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tbEscuelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                    .addComponent(comboFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnCrear)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEscuelaActionPerformed
        // TODO TODO Añadir esta accion
    }//GEN-LAST:event_txEscuelaActionPerformed

    private void comboFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFacultadActionPerformed
        // TODO Añadir esta accion
    }//GEN-LAST:event_comboFacultadActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (comboFacultad.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Primero seleccione una facultad");
        } else {
            /*Verificar si el txEscuela no está vacío ni formado por espacios*/
            String escuela = txEscuela.getText();
            escuela = escuela.trim();
            if (escuela.length() == 0) {
                JOptionPane.showMessageDialog(null, "Rellene la escuela correctamente");
            } else {
                String sqlCheck = String.format("select * from escuela where nombre='%s'", escuela);
                boolean check = Control.checkQuery(sqlCheck);
                System.out.println(sqlCheck + "  " + check);
                if (check) {
                    JOptionPane.showMessageDialog(null, "La escuela ya existe en está u otra facultad");
                } else {
                    String facultad = Objects.requireNonNull(comboFacultad.getSelectedItem()).toString();
                    String sqlCrear = String.format("call registrar_escuela('%s','%s')", escuela, facultad);
                    Control.updateTable(sqlCrear);
                    String sqlFacultad = String.format("select e.nombre from escuela e inner join facultad f on e.facultad_id=f.id "
                            + "where f.nombre='%s'", facultad);
                    Control.fillTable(md, sqlFacultad, 1);
                }
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBuscarActionPerformed
        // TODO Añadir esta accion
    }//GEN-LAST:event_txBuscarActionPerformed

    private void txBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyTyped
        if (md.getRowCount() > 0) {
            int pos = txBuscar.getCaretPosition();
            System.out.println(pos);
            String nombre = (txBuscar.getText().substring(0, pos) + evt.getKeyChar() + txBuscar.getText().substring(pos)).trim();
            String facultad = Objects.requireNonNull(comboFacultad.getSelectedItem()).toString();
            String sqlFacultad = "select e.nombre from escuela e inner join facultad f on e.facultad_id=f.id "
                    + "where f.nombre='" + facultad + "' and e.nombre like '" + nombre + "%';";
            Control.fillTable(md, sqlFacultad, 1);
        }
    }//GEN-LAST:event_txBuscarKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboFacultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEscuelas;
    private javax.swing.JTextField txBuscar;
    private javax.swing.JTextField txEscuela;
    // End of variables declaration//GEN-END:variables
}
