/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Control;
import clases.Report;
import java.awt.event.ItemEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pajas
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    private final JFrame padre;
    String selectedFacultad = "";
    String paramFacultad = "";

    public Reportes(JFrame padre) {
        this.padre = padre;
        initComponents();
        init();
        addComboFacultad();
    }

    public void init() {
        setLocationRelativeTo(null);
        setTitle("Reporte de alumnos vulnerables");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rbtnTodos.setSelected(true);
    }

    public void addComboFacultad() {
        String sqlCombo = "SELECT nombre FROM facultad";
        Control.fillCombo(comboFacultad, sqlCombo);
        comboFacultad.addItem("Todas las facultades");
        comboFacultad.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                selectedFacultad = e.getItem().toString();
                paramFacultad = (selectedFacultad.equalsIgnoreCase("Todas las facultades")) ? "%" : selectedFacultad;
            }
        });
        comboFacultad.setSelectedIndex(comboFacultad.getItemCount() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboFacultad = new javax.swing.JComboBox<>();
        rbtnFaltan = new javax.swing.JRadioButton();
        rbtnChip = new javax.swing.JRadioButton();
        rbtnLaptop = new javax.swing.JRadioButton();
        rbtnRecibio = new javax.swing.JRadioButton();
        rbtnTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reportes de alumnos vulnerables segun facultad");

        jButton1.setText("Generar reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Facultad:");

        comboFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFacultadActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnFaltan);
        rbtnFaltan.setText("Faltan chip y laptop");

        buttonGroup1.add(rbtnChip);
        rbtnChip.setText("Falta chip");
        rbtnChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChipActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnLaptop);
        rbtnLaptop.setText("Falta laptop");
        rbtnLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnLaptopActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRecibio);
        rbtnRecibio.setText("Recibio chip y laptop");
        rbtnRecibio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRecibioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTodos);
        rbtnTodos.setText("Todos los alumnos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(comboFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnRecibio)
                    .addComponent(rbtnLaptop)
                    .addComponent(rbtnChip)
                    .addComponent(rbtnFaltan)
                    .addComponent(rbtnTodos))
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(rbtnFaltan)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbtnChip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(rbtnLaptop)
                .addGap(18, 18, 18)
                .addComponent(rbtnRecibio)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFacultadActionPerformed
        // TODO Añadir esta acción
    }//GEN-LAST:event_comboFacultadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (rbtnTodos.isSelected()) {
            Report.showReport("src\\main\\java\\Reportes\\AlumnList.jasper", "facultad", paramFacultad);
        } else if (rbtnFaltan.isSelected()) {
            Report.showReport("src\\main\\java\\Reportes\\AlumnListFaltanAmbos.jasper", "facultad", paramFacultad);
        } else if (rbtnChip.isSelected()) {
            Report.showReport("src\\main\\java\\Reportes\\AlumnListChip.jasper", "facultad", paramFacultad);
        } else if (rbtnLaptop.isSelected()) {
            Report.showReport("src\\main\\java\\Reportes\\AlumnListLaptop.jasper", "facultad", paramFacultad);
        } else if (rbtnRecibio.isSelected()) {
            Report.showReport("src\\main\\java\\Reportes\\AlumnListRecibioAmbos.jasper", "facultad", paramFacultad);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtnLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnLaptopActionPerformed
    }//GEN-LAST:event_rbtnLaptopActionPerformed

    private void rbtnRecibioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRecibioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRecibioActionPerformed

    private void rbtnChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnChipActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void dispose() {
        padre.setExtendedState(NORMAL);
        padre.setVisible(true);
        super.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFacultad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbtnChip;
    private javax.swing.JRadioButton rbtnFaltan;
    private javax.swing.JRadioButton rbtnLaptop;
    private javax.swing.JRadioButton rbtnRecibio;
    private javax.swing.JRadioButton rbtnTodos;
    // End of variables declaration//GEN-END:variables
}
